#!/usr/bin/env python3
"""Render JSON-LD source-of-truth into human-readable Markdown view.

Drift-zero contract: this tool reads ONLY the JSON-LD files. The
generated Markdown under `docs/` is a derivative view, not a source of
truth. If you want to change the content, edit the JSON-LD and
regenerate.

Usage::

    python tools/render_md.py --data data --out docs

The script overwrites `docs/overview.md` and `docs/disputes.md`.
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# Allow running from repo root without install.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from loaders.python_minimal import Claim, IutGraph  # noqa: E402

logger = logging.getLogger(__name__)


GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by tools/render_md.py from data/*.json. "
    "DO NOT EDIT BY HAND. -->\n\n"
)


def render_overview(graph: IutGraph) -> str:
    """Render `docs/overview.md` from entities + claim summary."""
    parts: list[str] = [GENERATED_BANNER, "# IUT status — overview\n"]
    parts.append(
        "This page is auto-generated from `data/entities.json` and "
        "`data/claims.json`. The JSON-LD is the source of truth.\n\n"
    )

    sections: dict[str, list] = {}
    for entity in graph.entities.values():
        sections.setdefault(entity.section, []).append(entity)

    for section_name in sorted(sections):
        parts.append(f"## {section_name}\n\n")
        for entity in sorted(sections[section_name], key=lambda e: e.id):
            parts.append(f"### `{entity.id}` — {entity.label}\n\n")
            parts.append(f"- type: `{entity.type}`\n")
            if entity.alt_labels:
                parts.append(f"- aliases: {', '.join(entity.alt_labels)}\n")
            if entity.introduced_by:
                parts.append(f"- introduced by: {entity.introduced_by}\n")
            if entity.introduced_year:
                parts.append(f"- year: {entity.introduced_year}\n")
            if entity.depends_on:
                deps = ", ".join(f"`{d}`" for d in entity.depends_on)
                parts.append(f"- depends on: {deps}\n")
            if entity.lean_module:
                parts.append(f"- Lean module: `{entity.lean_module}`\n")
            related = graph.claims_about(entity.id)
            if related:
                parts.append(f"- claims about: {len(related)}\n")
            parts.append("\n")

    return "".join(parts)


def render_disputes(graph: IutGraph) -> str:
    """Render `docs/disputes.md` from claim graph (focus on contradictions)."""
    parts: list[str] = [GENERATED_BANNER, "# IUT disputes — claim graph view\n\n"]
    parts.append(
        "Each claim is presented with its proponents, position, evidence, "
        "and any counter- or supporting claims. The dispute is preserved; "
        "no synthesis is performed.\n\n"
    )

    parts.append("## Opposing pairs\n\n")
    pairs = graph.opposing_pairs()
    if not pairs:
        parts.append("(none recorded)\n\n")
    else:
        for counter, target in pairs:
            parts.append(f"- `{counter.id}` counters `{target.id}`\n")
            parts.append(f"  - {counter.label}\n")
            parts.append(f"  - vs: {target.label}\n")
        parts.append("\n")

    parts.append("## All claims\n\n")
    for claim in sorted(graph.claims.values(), key=lambda c: c.asserted_at):
        parts.append(_render_claim(claim, graph))

    return "".join(parts)


def _render_claim(claim: Claim, graph: IutGraph) -> str:
    parts: list[str] = []
    parts.append(f"### `{claim.id}`\n\n")
    parts.append(f"- label: {claim.label}\n")
    parts.append(f"- about: `{claim.about}`\n")
    parts.append(f"- position: **{claim.position}** / stance: **{claim.stance}**\n")
    parts.append(f"- proponents: {', '.join(claim.proponents)}\n")
    parts.append(f"- asserted: {claim.asserted_at}\n")
    if claim.counters:
        parts.append(f"- counters: {', '.join(f'`{c}`' for c in claim.counters)}\n")
    if claim.supports:
        parts.append(f"- supports: {', '.join(f'`{c}`' for c in claim.supports)}\n")
    parts.append("- evidence:\n")
    for ev_id in claim.evidence:
        ev = graph.evidence.get(ev_id)
        if ev and ev.url:
            parts.append(f"  - [{ev.label}]({ev.url})\n")
        elif ev:
            parts.append(f"  - {ev.label}\n")
        else:
            parts.append(f"  - `{ev_id}` (record not yet in evidence.json)\n")
    if claim.specific_objection:
        parts.append(f"- specific objection: {claim.specific_objection}\n")
    if claim.status:
        parts.append(f"- status: {claim.status}\n")
    parts.append(f"- verified at: {claim.verified_at}\n\n")
    return "".join(parts)


def render_timeline(graph: IutGraph) -> str:
    """Render `docs/timeline.md` chronologically."""
    parts: list[str] = [GENERATED_BANNER, "# IUT dispute timeline\n\n"]
    for ev in sorted(graph.timeline.values(), key=lambda e: e.date):
        actors = ", ".join(ev.actors) if ev.actors else "—"
        parts.append(f"- **{ev.date}** — {ev.label} (actors: {actors})\n")
    parts.append("\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description="render JSON-LD → Markdown view")
    parser.add_argument("--data", default="data")
    parser.add_argument("--out", default="docs")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(message)s",
    )

    graph = IutGraph.load(args.data)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "overview.md").write_text(render_overview(graph), encoding="utf-8")
    (out_dir / "disputes.md").write_text(render_disputes(graph), encoding="utf-8")
    (out_dir / "timeline.md").write_text(render_timeline(graph), encoding="utf-8")
    logger.info("rendered to %s/{overview,disputes,timeline}.md", out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
